export const myWorks =[
    {id:1,
    img:"images/eco2.png",
    link:"https://github.com/Hagar7/Watches-Ecommerce.git",
    btn:"Redux Toolkit",
    btn2:"Router Dom",
    btn3:"axios",
    btn4:"JSON Server",
    btn5:""
},
{id:2,
    img:"images/dash.png",
    link:"https://github.com/Hagar7/dashboard.git",
    btn:"Redux Toolkit",
    btn2:"Router Dom",
    btn3:"axios",
    btn4:"JSON Server",
    btn5:""
},
{id:3,
    img:"images/cienma.png",
    link:"https://cinema-rouge.vercel.app/#/login",
    btn:"Context",
    btn2:"Router Dom",
    btn3:"axios",
    btn4:"SASS",
    btn5:""
},
{id:4,
    img:"images/gam.png",
    link:"https://gaming-lemon.vercel.app/login",
    btn:"Context",
    btn2:"Router Dom",
    btn3:"axios",
    btn4:"Joi",
    btn5:"SASS"
},
{id:5,
    img:"images/eco.png",
    link:"https://zaadv.co/gogo/eco/",
    btn:"Redux Toolkit",
    btn2:"Router Dom",
    btn3:"axios",
    btn4:"SASS",
    btn5:""
},
{id:6,
    img:"images/first.png",
    link:"https://first-react-pro.vercel.app/",
    btn:"Bootstrap",
    btn2:"Router Dom",
    btn3:"axios",
    btn4:"SASS",
    btn5:""
},
{id:7,
    img:"images/reg.png",
    link:"https://hagar7.github.io/Registration/",
    btn:"Bootstrap",
    btn2:"JavaScript",
    btn3:"Api",
    btn4:"CSS",
    btn5:""
},
{id:8,
    img:"images/yummy.png",
    link:"https://hagar7.github.io/Yummy/",
    btn:"Bootstrap",
    btn2:"JavaScript",
    btn3:"Api",
    btn4:"CSS",
    btn5:""
},
{id:9,
    img:"images/book.png",
    link:"https://hagar7.github.io/Bookmark/",
    btn:"Bootstrap",
    btn2:"JavaScript",
    btn3:"CSS",
    btn4:"crud",
    btn5:""
},
{id:10,
    img:"images/dev.png",
    link:"https://hagar7.github.io/DevFolio/",
    btn:"Bootstrap",
    btn2:"JQuery",
    btn3:"CSS",
    btn4:"",
    btn5:""
},
{id:11,
    img:"images/simone.png",
    link:"https://hagar7.github.io/Simone-/",
    btn:"Bootstrap",
    btn2:"JQuery",
    btn3:"CSS",
    btn4:"",
    btn5:""
},
{id:12,
    img:"images/wedding.png",
    link:"https://hagar7.github.io/Weeding/",
    btn:"Bootstrap",
    btn2:"JQuery",
    btn3:"CSS",
    btn4:"",
    btn5:""
},
]

